MODEL:
  TYPE: vmamba2
  NAME: vssd_small
  DROP_PATH_RATE: 0.4
  VMAMBA2:
    EMBED_DIM: 96
    DEPTHS: [2, 4, 15, 4]
    NUM_HEADS: [ 4, 4, 8, 16 ]
    SIMPLE_DOWNSAMPLE: False
    SIMPLE_PATCH_EMBED: False
    SSD_EXPANSION: 1
    SSD_CHUNK_SIZE: 256
    LINEAR_ATTN_DUALITY: True
    SSD_POSITIVE_DA: True
    ATTN_TYPES: [ 'mamba2', 'mamba2', 'mamba2', 'standard' ]
    DROP_PATH_RATE: 0.4
    ASYNC_STATE: [ 12, 24, 48, 64 ]
    MLP_RATIO: 3.0
    RMT_DOWNSAMPLE: True
    RMT_PATCH_EMBED: True
    USE_CPE: True
    SSD_LINEAR_NORM: True
    EXP_DA: True
    ROPE: True
    #RES_SCALE: [False, False, True, True]
  DDP: 'torch'

TRAIN:
  EPOCHS: 300
  WARMUP_EPOCHS: 20
